### ISSUE TITLE
pythongis.org build error? 

### ISSUE THREAD

**Issue by ljwolf** [Python-GIS-book/site#132]
Hey folks! 

We (@darribas, @sjsrey, and I) were going to use this book as a reference in our "further reading" to provide more context/info on spatial joins & geoprocessing stuff. 

I noticed that pythongis.org seems down? I get the GitHub 404 page when accessing it. 

Are y'all still targeting [pythongis.org](https://pythongis.org) as your book website? Should we use a different website? In the short-term we can link directly to the readthedocs, but we're sending to print soon and wanted a more stable link. 

Thanks!

**Comment by HTenkanen** [comment]
Hi @ljwolf ! Sorry only now spotted your message. FYI: now the pythongis.org should be building and it has been updated with the latest edits. We will use the pythongis.org as the home for the project, so you can refer to that. 👍🏻
