### ISSUE TITLE
"data/addresses.shp: No such file or directory" in Part 2 Chapter 8 under "Adding layers to the map"

### ISSUE THREAD

**Issue by anjishnum** [Python-GIS-book/site#150]
I am unable to find the directory to make a pull request. Would appreciate if you could clarify where the file may exist.

**Comment by davewhipp** [comment]
Are you able to help with this issue @HTenkanen ?

**Comment by HTenkanen** [comment]
The files for Chapter 8 were indeed missing from Github, thanks for the note @anjishnum! They are now added and can currently be found under the `develop` branch here: https://github.com/Python-GIS-book/site/tree/develop/source/part2/chapter-08/data
