### ISSUE TITLE
code block seams to be wrong

### ISSUE THREAD

**Issue by Frontnerd** [Python-GIS-book/site#152]
https://github.com/Python-GIS-book/site/blob/d36450eaefa894ba63e935ab6744eda175ee0305/source/part1/chapter-03/md/01-data-manipulation.md?plain=1#L237C25-L237C25

**Comment by davewhipp** [comment]
Hi @Frontnerd . Took a while to notice this issue as we have many in the list of things to fix in the book, but this has been fixed in the develop branch in 6211a3d10d46fdf3cf040477026f09798f48c4b2.

Thanks for noticing!
