### ISSUE TITLE
6.1: shapely -> shapely.geometry

### ISSUE THREAD

**Issue by CJBarry** [Python-GIS-book/site#159]
The code needs `shapely.geometry.Point`, not simply `shapely.Point`.

**Comment by martinfleis** [comment]
That is incorrect. With shapely >=2, all geometry objects are exposed on top level. So `shapely.Point` is correct and is a recommended pattern.

**Comment by HTenkanen** [comment]
Indeed, as @martinfleis points out (thanks!), with the latest shapely versions, you can import the geometry objects directly on top level.
