### ISSUE TITLE
missing dataset austin_pop_2019.gpkg

### ISSUE THREAD

**Issue by biscotty666** [Python-GIS-book/site#183]
Referenced in Chapter 6.2.

Thank you for the book.

For an equivalent dataset to proceed with the chapter:

```
import geodatasets
data = gpd.read_file(geodatasets.data.geoda.seattle1.path)
pop_gdf = data[["FIPS", "TOT_POP", "geometry"]]
pop_gdf = pop_gdf.to_crs('epsg:3857')
```
This gives meters, so need to convert to km

**Comment by biscotty666** [comment]
Found it. My bad. Thanks again

**Comment by VuokkoH** [comment]
Great if you found the data. For others with the same issue; Data for each chapter is organized inside each chapter's notebook folder. So, for chapter 6, you will find the input data under `site/source/part2/chapter-06/nb/data`. Online here: https://github.com/Python-GIS-book/site/tree/master/source/part2/chapter-06/nb/data
