### ISSUE TITLE
Build with nbsphinx?

### ISSUE THREAD

**Issue by davewhipp** [Python-GIS-book/site#4]
I can't recall why we're not already building the pages with [nbsphinx](https://nbsphinx.readthedocs.io/). It seems the `page_builder.py` script does the same thing that can be done with nbsphinx, so is there any reason not to use nbsphinx?

**Comment by HTenkanen** [comment]
@davewhipp The reason for not using nbsphinx and use the custom `page_builder.py` is to enable integration of the `Thebelab` for our Sphinx site. The `page_builder.py` can also do some other tricks such as inject the [Hypothes.is](https://web.hypothes.is/) button which allows you to make personal notes and highlight text from the site.

**Comment by davewhipp** [comment]
Got it, thanks. Closing this.
